### ISSUE TITLE
Null value for the variable wmfBlock on line 150

### ISSUE THREAD

**Issue by jmorrisIII** [MadhukarMoogala/Forge-ExplodeText#1]
I have an issue running the EXPTXT command from accoreconsole. If I run it from the regular AutoCad Gui it works but from accoreconsole I get a null value for the variable wmfBlock on line 150. The entity from "SelectLastEnt" is a Polyline not a BlockReference. Any Ideas?
Thanks

`var wmfBlock = tr.GetObject(ed.SelectLastEnt(), OpenMode.ForWrite) as BlockReference;`

**Comment by jmorrisIII** [comment]
I was running EXPTXT in the same script file as the program that was generating the DBText. After running this in separate AccoreConsole command directly after completing the previous script it worked.

**Comment by MadhukarMoogala** [comment]
@jmorrisIII , Thanks for your patience.
I was on holiday, couldn't catch up.
Glad that you are able to use the app, please let me know for any further queries. I can close the issue for now.
