### ISSUE TITLE
"eInvalidInput" error when using the AutoCad 2019 version of AccoreConsole

### ISSUE THREAD

**Issue by jmorrisIII** [MadhukarMoogala/Forge-ExplodeText#2]
We are running AutoCad 2018 currently but will be moving to 2019 soon. When I run the same script and drawing flags with the AutoCad 2019 version of AccoreConsole I get the error "eInvalidInput" on the line shown below. Are you able to reproduce this?

ed.Command("_.WMFOUT", tempFile, "", "");

**Comment by MadhukarMoogala** [comment]
@Jmorissil Try  (arxload "acapp.crx") in your script before calling ExpTxt command. We moved wmf codebase to acapp.crx module.

**Comment by jmorrisIII** [comment]
That worked. Thanks for your help.
